<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>Irihi.Iconica.Demo.Browser</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Irihi.Iconica.Demo\Irihi.Iconica.Demo.csproj"/>
    </ItemGroup>
</Project>
