// See https://aka.ms/new-console-template for more information

using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using IconGenerator;

var rootPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
var svgPath = Path.Combine(rootPath, "iconpark", "packages", "react", "src", "icons");
var fileNames = Directory.GetFiles(svgPath, "*.tsx");
var sourceTargetPath = Path.Combine(rootPath, "src", "Irihi.Iconica", "Generated");

if (!Directory.Exists(sourceTargetPath))
    Directory.CreateDirectory(sourceTargetPath);

static string GenerateDocument(string name, List<DrawingElement> drawingElements)
{
    var sb = new StringBuilder();
    sb.AppendLine("// AutoGenerated by IconGenerator");
    sb.AppendLine("// Design CopyRight 2024 IconPark Authors");
    sb.AppendLine("// Generated CopyRight 2024 IRIHI Technology");
    sb.AppendLine("// Generated Date: " + DateTime.Today.Date);
    sb.AppendLine("using Avalonia;");
    sb.AppendLine("using Avalonia.Media;");
    sb.AppendLine("using Irihi.Iconica;");
    sb.AppendLine();
    sb.AppendLine("namespace Irihi.Iconica.Icons;");
    sb.AppendLine();
    sb.AppendLine($"public class {name}: IconicaBase");
    sb.AppendLine("{");
    sb.AppendLine("    private static readonly DrawingElement[]? StaticDrawingData =");
    sb.AppendLine("    [");

    foreach (var element in drawingElements)
    {
        if (element is PathDrawingElement pathData)
        {
            sb.AppendLine("        new PathDrawingElement()");
            sb.AppendLine("        {");
            sb.AppendLine($"            StrokeIndex = {pathData.StrokeIndex},");
            if (pathData.FillIndex >= 0) sb.AppendLine($"            FillIndex = {pathData.FillIndex},");
            sb.AppendLine($"            InheritStrokeWidth = {pathData.InheritStrokeWidth.ToString().ToLower()},");
            sb.AppendLine($"            InheritStrokeCap = {pathData.InheritStrokeCap.ToString().ToLower()},");
            sb.AppendLine($"            InheritStrokeJoin = {pathData.InheritStrokeJoin.ToString().ToLower()},");
            sb.AppendLine("            Data = StreamGeometry.Parse(");
            sb.AppendLine($"                \"{pathData.Data}\"),");
            if (!string.IsNullOrWhiteSpace(pathData.Transform))
                sb.AppendLine($"            Transform = {CreateMatrix(pathData.Transform)},");
            sb.AppendLine("        },");
        }
        else if (element is EllipseDrawingElement ellipseData)
        {
            sb.AppendLine("        new EllipseDrawingElement()");
            sb.AppendLine("        {");
            sb.AppendLine($"            RadiusX = {ellipseData.RadiusX},");
            sb.AppendLine($"            RadiusY = {ellipseData.RadiusY},");
            sb.AppendLine($"            X = {ellipseData.X},");
            sb.AppendLine($"            Y = {ellipseData.Y},");
            sb.AppendLine($"            StrokeIndex = {ellipseData.StrokeIndex},");
            if (ellipseData.FillIndex >= 0) sb.AppendLine($"            FillIndex = {ellipseData.FillIndex},");
            sb.AppendLine($"            InheritStrokeWidth = {ellipseData.InheritStrokeWidth.ToString().ToLower()},");
            sb.AppendLine($"            InheritStrokeCap = {ellipseData.InheritStrokeCap.ToString().ToLower()},");
            sb.AppendLine($"            InheritStrokeJoin = {ellipseData.InheritStrokeJoin.ToString().ToLower()},");
            if (!string.IsNullOrWhiteSpace(ellipseData.Transform))
                sb.AppendLine($"            Transform = {CreateMatrix(ellipseData.Transform)},");
            sb.AppendLine("        },");
        }
        else if (element is LineDrawingElement lineData)
        {
            sb.AppendLine("        new LineDrawingElement()");
            sb.AppendLine("        {");
            sb.AppendLine($"            X1 = {lineData.X1},");
            sb.AppendLine($"            Y1 = {lineData.Y1},");
            sb.AppendLine($"            X2 = {lineData.X2},");
            sb.AppendLine($"            Y2 = {lineData.Y2},");
            sb.AppendLine($"            StrokeIndex = {lineData.StrokeIndex},");
            if (lineData.FillIndex >= 0) sb.AppendLine($"            FillIndex = {lineData.FillIndex},");
            sb.AppendLine($"            InheritStrokeWidth = {lineData.InheritStrokeWidth.ToString().ToLower()},");
            sb.AppendLine($"            InheritStrokeCap = {lineData.InheritStrokeCap.ToString().ToLower()},");
            sb.AppendLine($"            InheritStrokeJoin = {lineData.InheritStrokeJoin.ToString().ToLower()},");
            if (!string.IsNullOrWhiteSpace(lineData.Transform))
                sb.AppendLine($"            Transform = {CreateMatrix(lineData.Transform)},");
            sb.AppendLine("        },");
        }
        else if (element is RectDrawingElement rectData)
        {
            sb.AppendLine("        new RectDrawingElement()");
            sb.AppendLine("        {");
            sb.AppendLine($"            Width = {rectData.Width},");
            sb.AppendLine($"            Height = {rectData.Height},");
            sb.AppendLine($"            X = {rectData.X},");
            sb.AppendLine($"            Y = {rectData.Y},");
            if (rectData.Rx.HasValue) sb.AppendLine($"            Rx = {rectData.Rx},");
            if (rectData.Ry.HasValue) sb.AppendLine($"            Ry = {rectData.Ry},");
            sb.AppendLine($"            StrokeIndex = {rectData.StrokeIndex},");
            if (rectData.FillIndex >= 0) sb.AppendLine($"            FillIndex = {rectData.FillIndex},");
            sb.AppendLine($"            InheritStrokeWidth = {rectData.InheritStrokeWidth.ToString().ToLower()},");
            sb.AppendLine($"            InheritStrokeCap = {rectData.InheritStrokeCap.ToString().ToLower()},");
            sb.AppendLine($"            InheritStrokeJoin = {rectData.InheritStrokeJoin.ToString().ToLower()},");
            if (!string.IsNullOrWhiteSpace(rectData.Transform))
                sb.AppendLine($"            Transform = {CreateMatrix(rectData.Transform)},");
            sb.AppendLine("        },");
        }
    }

    sb.AppendLine("    ];");
    sb.AppendLine();
    sb.AppendLine("    protected override DrawingElement[]? DrawingData => StaticDrawingData;");
    sb.AppendLine("}");

    return sb.ToString();
}

var index = 0;
foreach (var fileName in fileNames)
{
    index++;
    try
    {
        var name = Path.GetFileNameWithoutExtension(fileName);
        var fileContent = await File.ReadAllTextAsync(fileName);
        var match = Regex.Matches(fileContent, @"<svg\b[^>]*>([\s\S]*?)<\/svg>");
        var xmlDoc = new XmlDocument();
        var value = match.First().Value;
        value = value.Replace("{{", "{");
        value = value.Replace("}}", "}");
        value = value.Replace("{", "\"{");
        value = value.Replace("}", "}\"");
        xmlDoc.LoadXml(value);
        // Find all <path> elements
        var nodes = xmlDoc.SelectNodes(
            "svg/path | g/path | svg/circle | g/circle | svg/ellipse | g/ellipse | svg/rect | g/rect | svg/line | g/line");
        if (nodes?.Count is null or 0) continue;

        var list = new List<DrawingElement>();

        foreach (var node in nodes)
        {
            var xmlElement = (XmlElement)node;
            if (xmlElement.Name == "path")
            {
                var d = xmlElement.GetAttribute("d");
                var fill = xmlElement.GetAttribute("fill");
                var stroke = xmlElement.GetAttribute("stroke");
                var strokeWidth = xmlElement.GetAttribute("strokeWidth");
                var strokeLineCap = xmlElement.GetAttribute("strokeLinecap");
                var transform = xmlElement.GetAttribute("transform");
                var fillIndex = fill.Length > 0 ? fill[^3] - '0' : -1;
                var strokeIndex = stroke.Length > 0 ? stroke[^3] - '0' : -1;
                var inheritStrokeWidth = strokeWidth.Length > 0;
                var inheritStrokeCap = strokeLineCap.Length > 0;
                var inheritStrokeJoin = strokeLineCap.Length > 0;

                var pathData = new PathDrawingElement
                {
                    Data = d,
                    FillIndex = fillIndex,
                    StrokeIndex = strokeIndex,
                    InheritStrokeWidth = inheritStrokeWidth,
                    InheritStrokeCap = inheritStrokeCap,
                    InheritStrokeJoin = inheritStrokeJoin,
                    Transform = transform
                };
                list.Add(pathData);
            }
            else if (xmlElement.Name == "circle")
            {
                var cx = xmlElement.GetAttribute("cx");
                var cy = xmlElement.GetAttribute("cy");
                var r = xmlElement.GetAttribute("r");
                var fill = xmlElement.GetAttribute("fill");
                var stroke = xmlElement.GetAttribute("stroke");
                var strokeWidth = xmlElement.GetAttribute("strokeWidth");
                var strokeLineCap = xmlElement.GetAttribute("strokeLinecap");
                var transform = xmlElement.GetAttribute("transform");
                var fillIndex = fill.Length > 0 ? fill[^3] - '0' : -1;
                var strokeIndex = stroke.Length > 0 ? stroke[^3] - '0' : -1;
                var inheritStrokeWidth = strokeWidth.Length > 0;
                var inheritStrokeCap = strokeLineCap.Length > 0;
                var inheritStrokeJoin = strokeLineCap.Length > 0;

                var ellipseData = new EllipseDrawingElement
                {
                    X = cx.Length > 0 ? double.Parse(cx) : 0,
                    Y = cy.Length > 0 ? double.Parse(cy) : 0,
                    RadiusX = r.Length > 0 ? double.Parse(r) : 0,
                    RadiusY = r.Length > 0 ? double.Parse(r) : 0,
                    FillIndex = fillIndex,
                    StrokeIndex = strokeIndex,
                    InheritStrokeWidth = inheritStrokeWidth,
                    InheritStrokeCap = inheritStrokeCap,
                    InheritStrokeJoin = inheritStrokeJoin,
                    Transform = transform
                };
                list.Add(ellipseData);
            }
            else if (xmlElement.Name == "ellipse")
            {
                var cx = xmlElement.GetAttribute("cx");
                var cy = xmlElement.GetAttribute("cy");
                var rx = xmlElement.GetAttribute("rx");
                var ry = xmlElement.GetAttribute("ry");
                var fill = xmlElement.GetAttribute("fill");
                var stroke = xmlElement.GetAttribute("stroke");
                var strokeWidth = xmlElement.GetAttribute("strokeWidth");
                var strokeLineCap = xmlElement.GetAttribute("strokeLinecap");
                var transform = xmlElement.GetAttribute("transform");
                var fillIndex = fill.Length > 0 ? fill[^3] - '0' : -1;
                var strokeIndex = stroke.Length > 0 ? stroke[^3] - '0' : -1;
                var inheritStrokeWidth = strokeWidth.Length > 0;
                var inheritStrokeCap = strokeLineCap.Length > 0;
                var inheritStrokeJoin = strokeLineCap.Length > 0;

                var ellipseData = new EllipseDrawingElement
                {
                    X = cx.Length > 0 ? double.Parse(cx) : 0,
                    Y = cy.Length > 0 ? double.Parse(cy) : 0,
                    RadiusX = rx.Length > 0 ? double.Parse(rx) : 0,
                    RadiusY = ry.Length > 0 ? double.Parse(ry) : 0,
                    FillIndex = fillIndex,
                    StrokeIndex = strokeIndex,
                    InheritStrokeWidth = inheritStrokeWidth,
                    InheritStrokeCap = inheritStrokeCap,
                    InheritStrokeJoin = inheritStrokeJoin,
                    Transform = transform
                };
                list.Add(ellipseData);
            }
            else if (xmlElement.Name == "rect")
            {
                var x = xmlElement.GetAttribute("x");
                var y = xmlElement.GetAttribute("y");
                var width = xmlElement.GetAttribute("width");
                var height = xmlElement.GetAttribute("height");
                var rx = xmlElement.GetAttribute("rx");
                var ry = xmlElement.GetAttribute("ry");
                var fill = xmlElement.GetAttribute("fill");
                var stroke = xmlElement.GetAttribute("stroke");
                var strokeWidth = xmlElement.GetAttribute("strokeWidth");
                var strokeLineCap = xmlElement.GetAttribute("strokeLinecap");
                var transform = xmlElement.GetAttribute("transform");
                var fillIndex = fill.Length > 0 ? fill[^3] - '0' : -1;
                var strokeIndex = stroke.Length > 0 ? stroke[^3] - '0' : -1;
                var inheritStrokeWidth = strokeWidth.Length > 0;
                var inheritStrokeCap = strokeLineCap.Length > 0;
                var inheritStrokeJoin = strokeLineCap.Length > 0;

                var rectData = new RectDrawingElement
                {
                    X = x.Length > 0 ? double.Parse(x) : 0,
                    Y = y.Length > 0 ? double.Parse(y) : 0,
                    Width = width.Length > 0 ? double.Parse(width) : 0,
                    Height = height.Length > 0 ? double.Parse(height) : 0,
                    Rx = rx.Length > 0 ? double.Parse(rx) : null,
                    Ry = ry.Length > 0 ? double.Parse(ry) : null,
                    FillIndex = fillIndex,
                    StrokeIndex = strokeIndex,
                    InheritStrokeWidth = inheritStrokeWidth,
                    InheritStrokeCap = inheritStrokeCap,
                    InheritStrokeJoin = inheritStrokeJoin,
                    Transform = transform
                };
                list.Add(rectData);
            }
            else if (xmlElement.Name == "line")
            {
                var x1 = xmlElement.GetAttribute("x1");
                var y1 = xmlElement.GetAttribute("y1");
                var x2 = xmlElement.GetAttribute("x2");
                var y2 = xmlElement.GetAttribute("y2");
                var fill = xmlElement.GetAttribute("fill");
                var stroke = xmlElement.GetAttribute("stroke");
                var strokeWidth = xmlElement.GetAttribute("strokeWidth");
                var strokeLineCap = xmlElement.GetAttribute("strokeLinecap");
                var transform = xmlElement.GetAttribute("transform");
                var fillIndex = fill.Length > 0 ? fill[^3] - '0' : -1;
                var strokeIndex = stroke.Length > 0 ? stroke[^3] - '0' : -1;
                var inheritStrokeWidth = strokeWidth.Length > 0;
                var inheritStrokeCap = strokeLineCap.Length > 0;
                var inheritStrokeJoin = strokeLineCap.Length > 0;

                var lineData = new LineDrawingElement
                {
                    X1 = x1.Length > 0 ? double.Parse(x1) : 0,
                    Y1 = y1.Length > 0 ? double.Parse(y1) : 0,
                    X2 = x2.Length > 0 ? double.Parse(x2) : 0,
                    Y2 = y2.Length > 0 ? double.Parse(y2) : 0,
                    FillIndex = fillIndex,
                    StrokeIndex = strokeIndex,
                    InheritStrokeWidth = inheritStrokeWidth,
                    InheritStrokeCap = inheritStrokeCap,
                    InheritStrokeJoin = inheritStrokeJoin,
                    Transform = transform
                };
                list.Add(lineData);
            }
        }

        var sourceCode = GenerateDocument(name, list);

        var targetPath = Path.Combine(sourceTargetPath, $"{name}.cs");

        await File.WriteAllTextAsync(targetPath, sourceCode);
        Debug.Write(".");
        if (index % 50 == 0)
            Debug.WriteLine(string.Empty);
        // Debug.WriteLine($"Generated {name}.cs");
    }
    catch (Exception e)
    {
        Debug.WriteLine(string.Empty);
        Debug.WriteLine(fileName);
        Debug.WriteLine(e.Message);
    }
}

static string? CreateMatrix(string? transformString)
{
    if (string.IsNullOrEmpty(transformString)) return null;
    if (transformString.StartsWith("matrix"))
    {
        var values = transformString.Split('(')[1].Split(')')[0].Split(' ', StringSplitOptions.RemoveEmptyEntries);
        return $"new Matrix({values[0]}, {values[1]}, {values[2]}, {values[3]}, {values[4]}, {values[5]})";
    }

    if (transformString.StartsWith("rotate"))
    {
        // values: angle, x, y
        var values = transformString.Split('(')[1].Split(')')[0].Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (values.Length == 1)
            return
                $"Matrix.CreateRotation({values[0]})";
        var angle = double.Parse(values[0]);
        var x = double.Parse(values[1]);
        var y = double.Parse(values[2]);

        var radians = angle * (Math.PI / 180.0);
        var cos = Math.Cos(radians);
        var sin = Math.Sin(radians);

        return $"new Matrix({cos}, {sin}, {-sin}, {cos}, {x * (1.0 - cos) + y * sin}, {y * (1.0 - cos) - x * sin})";
    }

    return null;
}